export declare const IMPORT_FROM_DEPENDENCE_RE: RegExp;
export declare const EXPORT_FROM_DEPENDENCE_RE: RegExp;
export declare const IMPORT_DEPENDENCE_RE: RegExp;
export declare const scriptExtNames: string[];
export declare const styleExtNames: string[];
export declare const scriptIndexes: string[];
export declare const styleIndexes: string[];
export declare const tryMatchExtname: (file: string, extname: string[]) => string | undefined;
export declare const resolveDependence: (file: string, script: string) => string;
export declare function compileScript(script: string, file: string): Promise<void>;
export declare function compileScriptFile(file: string): Promise<void>;
export declare function getScriptExtname(): string;
export declare function compileESEntry(dir: string, publicDirs: string[]): Promise<void>;
