export declare const dirname: string;
export declare const CWD: string;
export declare const VARLET_CONFIG: string;
export declare const SRC_DIR: string;
export declare const ES_DIR: string;
export declare const LIB_DIR: string;
export declare const UMD_DIR: string;
export declare const TYPES_DIR: string;
export declare const ROOT_DOCS_DIR: string;
export declare const ROOT_PAGES_DIR: string;
export declare const ESLINT_EXTENSIONS: string[];
export declare const VITE_RESOLVE_EXTENSIONS: string[];
export declare const SCRIPTS_EXTENSIONS: string[];
export declare const PUBLIC_DIR_INDEXES: string[];
export declare const STYLE_DIR_NAME = "style";
export declare const EXAMPLE_DIR_NAME = "example";
export declare const LOCALE_DIR_NAME = "locale";
export declare const DOCS_DIR_NAME = "docs";
export declare const TESTS_DIR_NAME = "__tests__";
export declare const GENERATORS_DIR: string;
export declare const UI_PACKAGE_JSON: string;
export declare const CLI_PACKAGE_JSON: string;
export declare const CHECKLIST_FILE: string;
export declare const SITE: string;
export declare const SITE_OUTPUT_PATH: string;
export declare const SITE_PUBLIC_PATH: string;
export declare const SITE_DIR: string;
export declare const SITE_PC_DIR: string;
export declare const HL_DIR: string;
export declare const HL_COMPONENT_NAME_RE: RegExp;
export declare const HL_API_RE: RegExp;
export declare const HL_EN_TITLE_ATTRIBUTES_RE: RegExp;
export declare const HL_EN_TITLE_EVENTS_RE: RegExp;
export declare const HL_EN_TITLE_SLOTS_RE: RegExp;
export declare const HL_EN_MD = "en-US.md";
export declare const HL_EN_WEB_TYPES_JSON: string;
export declare const HL_ZH_TITLE_ATTRIBUTES_RE: RegExp;
export declare const HL_ZH_TITLE_EVENTS_RE: RegExp;
export declare const HL_ZH_TITLE_SLOTS_RE: RegExp;
export declare const HL_ZH_MD = "zh-CN.md";
export declare const HL_ZH_WEB_TYPES_JSON: string;
export declare const ICONS_DIST_DIR: string;
export declare const ICONS_CSS_DIR: string;
export declare const ICONS_PNG_DIR: string;
export declare const ICONS_FONTS_DIR: string;
export declare const ICONS_SVG_DIR: string;
export declare const EXTENSION_ENTRY: string;
export declare const JEST_CONFIG: string;
